# Defines analysis rules for Dart and Flutter
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    # Treat these as errors
    missing_required_param: error
    missing_return: error
    invalid_annotation_target: error

    # Memory & performance
    close_sinks: error
    cancel_subscriptions: error

    # Warnings
    unused_import: warning
    unused_element: warning
    avoid_print: warning
    prefer_const_constructors: warning
    prefer_const_literals_to_create_immutables: warning

    # Info
    todo: info
    deprecated_member_use: info

linter:
  rules:
    # Error prevention
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - no_duplicate_case_values
    - valid_regexps
    - use_build_context_synchronously
    - avoid_slow_async_io
    - avoid_web_libraries_in_flutter

    # Style
    - camel_case_types
    - constant_identifier_names
    - directives_ordering
    - file_names
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - curly_braces_in_flow_control_structures
    - require_trailing_commas

    # Performance & Memory
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - avoid_function_literals_in_foreach_calls
    - prefer_collection_literals
    - unnecessary_lambdas
    - avoid_unnecessary_containers

    # Best practices
    - always_declare_return_types
    - annotate_overrides
    - await_only_futures
    - prefer_final_fields
    - prefer_final_locals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - unnecessary_const
    - unnecessary_new
    - unnecessary_this
    - use_rethrow_when_possible
    - use_key_in_widget_constructors
    - sized_box_for_whitespace
    - avoid_returning_null_for_void
    - sort_child_properties_last

    # Code quality
    - prefer_if_null_operators
    - prefer_null_aware_operators
    - unnecessary_null_in_if_null_operators
    - unnecessary_parenthesis
    - unawaited_futures

    # Security
    - secure_pubspec_urls
