# Defines analysis rules for Dart and Flutter
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"

  errors:
    missing_required_param: error
    missing_return: error
    unused_import: warning
    unused_element: warning
    avoid_print: warning
    prefer_const_constructors: warning
    prefer_const_literals_to_create_immutables: warning

linter:
  rules:
    # Error prevention
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - no_duplicate_case_values
    - valid_regexps

    # Style
    - camel_case_types
    - constant_identifier_names
    - directives_ordering
    - file_names
    - library_names
    - library_prefixes
    - non_constant_identifier_names

    # Performance
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables

    # Best practices
    - always_declare_return_types
    - annotate_overrides
    - await_only_futures
    - prefer_final_fields
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - unnecessary_const
    - unnecessary_new
    - use_rethrow_when_possible
